In [171]:
import scanpy as sc
import pandas as pd
import anndata as ad
#data_path为文件所在的文件夹的目录
data_path = './data/Slide-seq_Coronal_cerebellum'
count_file = 'MappedDGEForR.csv'
meta_file = 'BeadLocationsForR.csv'
# 用pandas读取csv
count0 = pd.read_csv(f'{data_path}/{count_file}')
meta = pd.read_csv(f'{data_path}/{meta_file}')

In [172]:
count0

,Row,TCGGAACAGAAAAC,TAGGTTCTAGGAAT,CAGCGCGGGCCGGC,ACTTTTTCAGAAAT,AGTGCTTGAGAAAN,AGACGCCAGAGACG,GAGTTGCGCTAAAG,CTTTTATCGATAAA,GATTAAAAGCGCTC,...,TGTACGTTTATCGT,GATGAAGTATCGAC,TCTACTGTTATATC,TCGACCCTGATCGA,TCCTGTGTCGCGCT,TGGAGATTCGCGCT,CTGTTTTTCGCGCT,TCTCTGGTCGCGAN,CGCGCGTTCGCGCG,ACGGCCTTATAGCG
0,0610005C13Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0610007P14Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0610009B22Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0610009L18Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0610009O20Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18128,mt-Tv,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18129,n-R5-8s1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18130,n-R5s197,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18131,n-R5s48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18132,n-R5s58,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [173]:
#行列转置
count=count0.values[:,1:].T

In [174]:
#提取cellID
cell_id_array = count0.columns[1:]
cell_id_array

Index(['TCGGAACAGAAAAC', 'TAGGTTCTAGGAAT', 'CAGCGCGGGCCGGC', 'ACTTTTTCAGAAAT',
       'AGTGCTTGAGAAAN', 'AGACGCCAGAGACG', 'GAGTTGCGCTAAAG', 'CTTTTATCGATAAA',
       'GATTAAAAGCGCTC', 'GGTAAGGGCTATAG',
       ...
       'TGTACGTTTATCGT', 'GATGAAGTATCGAC', 'TCTACTGTTATATC', 'TCGACCCTGATCGA',
       'TCCTGTGTCGCGCT', 'TGGAGATTCGCGCT', 'CTGTTTTTCGCGCT', 'TCTCTGGTCGCGAN',
       'CGCGCGTTCGCGCG', 'ACGGCCTTATAGCG'],
      dtype='object', length=26404)

In [175]:
#提取geneID
gene_id_array = count0['Row']
gene_id_array

0        0610005C13Rik
1        0610007P14Rik
2        0610009B22Rik
3        0610009L18Rik
4        0610009O20Rik
             ...
18128            mt-Tv
18129         n-R5-8s1
18130         n-R5s197
18131          n-R5s48
18132          n-R5s58
Name: Row, Length: 18133, dtype: object

In [176]:
# 提取count_matrix
count_X = count.astype('float')

In [177]:
# 构建adata
adata = ad.AnnData(count_X)
adata.var_names = gene_id_array
adata.obs_names = cell_id_array

/tmp/ipykernel_192442/3501277586.py:2: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  adata = ad.AnnData(count_X)

In [178]:
meta = pd.read_csv(f'{data_path}/{meta_file}')
meta

             barcodes       xcoord       ycoord
0      TCGGAACAGAAAAC  2357.370370  1805.240741
1      TAGGTTCTAGGAAT  2263.741935   929.370968
2      CAGCGCGGGCCGGC  4885.615385  4656.353846
3      ACTTTTTCAGAAAT  3368.285714  5590.304762
4      AGTGCTTGAGAAAN  2515.765217  1008.321739
...               ...          ...          ...
26399  TGGAGATTCGCGCT  2508.453237  3330.899281
26400  CTGTTTTTCGCGCT  3838.413333  1863.720000
26401  TCTCTGGTCGCGAN  2419.077778  1817.488889
26402  CGCGCGTTCGCGCG  4766.520548  3519.616438
26403  ACGGCCTTATAGCG  2521.437500   767.604167

[26404 rows x 3 columns]

In [179]:
# 需要把细胞名作为index，与adata的细胞名align起来
meta = meta.set_index('barcodes')

In [180]:
adata.obsm['spatial'] = meta.loc[adata.obs_names].loc[:,['xcoord','ycoord']]

In [181]:
adata

AnnData object with n_obs × n_vars = 26404 × 18133
    obsm: 'spatial'

In [182]:
adata.write_h5ad(f'{data_path}/Puck_180819_18.h5ad')